from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

module get_data:
	snakefile: "rules/get_data.smk"
	config: config

use rule download_NeurIPS2021 from get_data
